[project]
name = "fastapi-memory-benchmark"
version = "0.0.1"
requires-python = ">=3.11,<4.0"
dependencies = [
    "fastapi[all]>=0.115.12,<0.116.0",
    "pydantic>=2.11.4,<3.0.0",
    "psutil>=7.0.0,<8.0.0",
]

[tool.uv]
package = false
