[project]
name = "litestar-memory-benchmark"
version = "0.0.1"
requires-python = ">=3.11,<4.0"
dependencies = [
    "litestar[standard]>=2.16.0,<3.0.0",
    "psutil>=7.0.0,<8.0.0",
]

[tool.uv]
package = false
